# Generated by Django 3.0 on 2019-12-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('accounts', '0002_auto_20191203_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doors',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_doors', to='catalog.Door'),
        ),
    ]
