# Generated by Django 2.2.6 on 2019-10-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='What is your name?', max_length=100)),
                ('email', models.EmailField(default='DEFAULT', max_length=254)),
                ('user_public_key', models.CharField(default='DEFAULT', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('door_public_key', models.CharField(default='DEFAULT', max_length=256)),
                ('user_list', models.ManyToManyField(help_text='List of Authorized Users', to='catalog.User')),
            ],
        ),
    ]
