# Generated by Django 2.2.6 on 2019-10-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='user_list',
        ),
    ]
