# Generated by Django 2.2.6 on 2019-10-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_door_user_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='door_public_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_public_key',
        ),
    ]
