# Generated by Django 2.2.6 on 2019-12-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_externalinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalInput',
        ),
    ]
