# Generated by Django 2.2.6 on 2019-10-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191030_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='door_accessed',
        ),
        migrations.AddField(
            model_name='user',
            name='door_accessed',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='catalog.Door'),
            preserve_default='True',
        ),
    ]
