# Generated by Django 2.2.6 on 2019-12-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_externalinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='door_private_key',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
