# Generated by Django 2.2.6 on 2019-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191030_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='door_accessed',
        ),
        migrations.AddField(
            model_name='user',
            name='door',
            field=models.ManyToManyField(to='catalog.Door'),
        ),
    ]
