# Generated by Django 2.2.6 on 2019-10-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191030_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='netid',
            field=models.CharField(help_text='What is your NetID?', max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_public_key',
            field=models.CharField(max_length=256, null='True'),
        ),
    ]
