# Generated by Django 2.2.6 on 2019-10-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191030_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_status',
            field=models.CharField(choices=[('N/A', 'N/A'), ('P', 'Pending'), ('D', 'Denied'), ('A', 'Approved')], default='N/A', max_length=1),
        ),
    ]
