# Generated by Django 2.2.6 on 2019-10-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191030_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='request_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='door',
            field=models.ManyToManyField(to='catalog.Door'),
        ),
    ]
