# Generated by Django 2.2.6 on 2019-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20191030_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_public_key',
            field=models.CharField(default='DEFAULT', max_length=256),
        ),
    ]
